# Generated by Django 2.2 on 2021-03-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_video_fetch_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoinformation',
            old_name='description',
            new_name='video_description',
        ),
        migrations.RenameField(
            model_name='videoinformation',
            old_name='publishedDateTime',
            new_name='video_publishedDateTime',
        ),
        migrations.RemoveField(
            model_name='videoinformation',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='videoinformation',
            name='channel_title',
        ),
        migrations.RemoveField(
            model_name='videoinformation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='videoinformation',
            name='thumbnailsUrls',
        ),
    ]
